name: Main workflow - deploy latest
run-name: ${{ github.event.head_commit.author.name }} - ${{ github.event.head_commit.message }}
on: 
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pre-ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ~/centos/demeter-discord-bot
            git pull origin master
            git status
            npm install --omit=dev
            pm2 restart demeter-discord-bot
            
