name: Main workflow - deploy latest
run-name: ${{ github.event.head_commit.author.name }} - ${{ github.event.head_commit.message }}
on: 
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ssh-scp-ssh-pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASSWORD }}
          first_ssh: pkill -f node
          scp: |
            '.' => /home/centos/demeter/
          last_ssh: npm start
      
