name: Main workflow - deploy latest
run-name: ${{ github.event.head_commit.author.name }} - ${{ github.event.head_commit.message }}
on: 
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: test1
        run: echo "this is a test"
      - name: test2
        run: echo ${{ secrets.SSH_HOST }} | sed 's/./& /g'
      - uses: actions/checkout@v3
      - name: pre-ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            pkill -f node 2>&1 > /dev/null
      - name: scp-skip-images
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "src,package.json"
          target: "/home/centos/demeter"
      - name: post-ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd demeter
            npm install
            npm start
            
